### ISSUE TITLE
I don't have Gans365. I'm having issue to capture in a room with electric light

### ISSUE THREAD

**Issue by neuberfran** [VickneshB/Mines#1]
This is my cube model:
![cubo](https://user-images.githubusercontent.com/38701397/110028134-a15bdc00-7d11-11eb-90a6-5e284572445f.jpg)

i need help adapting your project to my cube type

**Comment by VickneshB** [comment]
The program's threshold values and the color ranges were adjusted to my cube and that day's light setting. I am still working on the program to adjust to most light settings. But the best solution now would be to play with those thresholds and ranges to make it work for you.
