### ISSUE TITLE
error in code

### ISSUE THREAD

**Issue by RiddSarav** [VickneshB/Mines#3]
Traceback (most recent call last):
  File "main.py", line 463, in <module>
    main()
  File "main.py", line 402, in main
    [up_face, right_face, front_face, down_face, left_face, back_face] = up_ccw(video, videoWriter, up_face, right_face, front_face, down_face, left_face, back_face)
NameError: name 'up_ccw' is not defined
[ WARN:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-oduouqig\opencv\modules\videoio\src\cap_msmf.cpp (434) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

is the error i get ideas on how to fix it?

**Comment by VickneshB** [comment]
Do you have the other file too in the same directory? rotate.py file


Best,

Vicknesh Balabaskaran

**Comment by RiddSarav** [comment]
yes I just cloned the repository

**Comment by RiddSarav** [comment]
as soon as 1 rotation is over it closes abruptly it gives the right notation to solve the cube but no arrows

**Comment by VickneshB** [comment]
What's the error after it closes?


Best,

Vicknesh Balabaskaran

**Comment by RiddSarav** [comment]
the same error as posted above

**Comment by VickneshB** [comment]
Try this fix.
https://stackoverflow.com/questions/60007427/cv2-warn0-global-cap-msmf-cpp-674-sourcereadercbsourcereadercb-termina


Best,

Vicknesh Balabaskaran

**Comment by RiddSarav** [comment]
I run the code and it works but when i turn it after the first time it shuts down and gives me the right notation but no lines what do i do?

**Comment by VickneshB** [comment]
I've never seen this issue before. Try re cloning the repo. Else I need to
debug this issue which can't be done remotely.


Best,

Vicknesh Balabaskaran

**Comment by RiddSarav** [comment]
i will try recloning
